//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventoRelacion
    {
        public int EvPadreId { get; set; }
        public int EvHijoId { get; set; }
        public bool Activado { get; set; }
        public string Operador { get; set; }
    
        public virtual Evento Evento { get; set; }
        public virtual Evento Evento1 { get; set; }
    }
}
