//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBTSI1Entities : DbContext
    {
        public DBTSI1Entities()
            : base("name=DBTSI1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chat> Chat { get; set; }
        public virtual DbSet<chat_msg> chat_msg { get; set; }
        public virtual DbSet<Evento> Evento { get; set; }
        public virtual DbSet<EventoRelacion> EventoRelacion { get; set; }
        public virtual DbSet<EventoSubscripcion> EventoSubscripcion { get; set; }
        public virtual DbSet<HistoricoEvento> HistoricoEvento { get; set; }
        public virtual DbSet<Sensores> Sensores { get; set; }
        public virtual DbSet<Tipo_Sensor> Tipo_Sensor { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Valores> Valores { get; set; }
    }
}
